name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src
        
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2

    - uses: actions/upload-artifact@v2
      with:
        name: notchx
        path: src/dist/windows
        
    - uses: actions/upload-artifact@v2
      with:
        name: notchx
        path: src/dist/linux
